{
 "title": "test",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "IAD GTM Capacity / Load / Target",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "expr": "sum(machine_cpu_cores * 100)", "legendFormat": "Current Capacity" },
    {
     "expr": "sum(machine_cpu_cores) * 100 * .6",
     "legendFormat": "Target Load"
    },
    {
     "expr": "sum(rate(node_cpu_seconds_total{mode!=\"idle\"}[2m]))*100",
     "legendFormat": "Current Load "
    }
   ]
  },
  {
   "title": "ORD GTM Capacity / Load / Target",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    { "expr": "sum(machine_cpu_cores * 100)", "legendFormat": "Current Capacity" },
    {
     "expr": "sum(machine_cpu_cores) * 100 * .6",
     "legendFormat": "Target Load"
    },
    {
     "expr": "sum(rate(node_cpu_seconds_total{mode!=\"idle\"}[2m]))*100",
     "legendFormat": "Current Load "
    }
   ]
  },
  {
   "title": "IAD - Outbound Traffic",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(node_network_transmit_bytes_total[2m])) /1000000 * 8",
     "legendFormat": "Mbps"
    }
   ]
  },
  {
   "title": "ORD - Outbound Traffic",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(node_network_transmit_bytes_total[2m])) /1000000 * 8",
     "legendFormat": "Mbps"
    }
   ]
  },
  {
   "title": "IAD CPU Utilization (1-100)",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(node_cpu_seconds_total{mode!=\"idle\"}[2m]))*100 / sum (machine_cpu_cores)"
    }
   ]
  },
  {
   "title": "ORD CPU Utilization (1-100)",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(node_cpu_seconds_total{mode!=\"idle\"}[2m]))*100 / sum (machine_cpu_cores)"
    }
   ]
  }
 ]
}